config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "notifications/:id/link_through", to: "notifications#link_through", as: :link_through
  devise_for :users
  resources :users, only: [:edit, :update, :show] do
    member do
      get :following, :followers
    end
    resources :likes, only: [:index], shallow: true
  end
  resources :music, only: [:index]
  resources :movie, only: [:index]
  resources :posts, only: [:new, :create, :destroy] do
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  POSTS_PER_PAGE = 6
  before_action :authenticate_user!, only: [:create, :destroy, :index]
  after_action :create_notifications, only: [:create]

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to do |format|
        format.html { redirect_to request.referrer }
        format.js
      end
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to do |format|
        format.html { redirect_to request.referrer }
        format.js
      end
    end
  end

  def index
    @user = User.find(params[:user_id])
    @posts = Post.joins(likes: :user).includes(likes: :user).where(likes: { user_id: @user.id }).order("likes.created_at DESC").page(params[:page]).per(POSTS_PER_PAGE)
  end

  private

  def like_params
    params.permit(:post_id)
  end

  def create_notifications
    return if @post.user.id == current_user.id
    Notification.create(user_id: @post.user_id, notified_by_id: current_user.id, post_id: @post.id, notified_type: "いいね")
  end
end

app/views/likes/create.js.erb
$("#post-like-<%= @post.id.to_s %>").
  html('<%= link_to image_tag("heart.png", size: "30x30"), like_path(@post.liked_by(current_user)), method: :delete, remote: true, class: "no-love" %><p><%= @post.likes.count %>件</p>');

app/views/likes/destroy.js.erb
$("#post-like-<%= @post.id.to_s %>").
  html('<%= link_to image_tag("no-heart.png", size: "30x30"), post_likes_path(@post), method: :post, remote: true, class: "love" %><p><%= @post.likes.count %>件</p>')

app/views/likes/index.html.erb
<%= provide(:title, "#{@user.username}がいいねした投稿") %>
<div class="user-info">
  <%= image_tag @user.image.thumb.url, size: "100x100" ,class: "rounded-circle" %>
  <h2><%= @user.username %></h2>
  <section class="stats">
    <%= render 'shared/stats', user: @user %>
  </section>
  <%= render 'users/follow_form', user: @user %>
</div>

<div class="post-like-switching mx-auto">
  <ul class=row>
    <%= link_to user_path(@user) do %>
      <li>投稿一覧</li>
    <% end %>
    <%= link_to user_likes_path(@user) do %>
      <li class="active">いいねした投稿一覧</li>
    <% end %>
  </ul>
</div>

<div class="post-list">
  <%= render 'posts/post_list' %>
</div>