config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "notifications/:id/link_through", to: "notifications#link_through", as: :link_through
  devise_for :users
  resources :users, only: [:edit, :update, :show] do
    member do
      get :following, :followers
    end
    resources :likes, only: [:index], shallow: true
  end
  resources :music, only: [:index]
  resources :movie, only: [:index]
  resources :posts, only: [:new, :create, :destroy] do
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_category.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag "movie-icon.jpeg", size: "128x128" %>
    <h2>Movie</h2>
    <p>お気に入りの映画について投稿しよう</p>
    <%= link_to "投稿をチェックする", movie_index_path, class: "btn btn-outline-secondary" %>
  </div>
  <div class="col-md-4">
    <%= image_tag "music-icon.jpeg", size: "128x128" %>
    <h2>Music</h2>
    <p>お気に入りの音楽について投稿しよう</p>
    <%= link_to "投稿をチェックする", music_index_path, class: "btn btn-outline-secondary" %>
  </div>
  <div class="col-md-4">
    <%= image_tag "book-icon.jpeg", size: "128x128" %>
    <h2>Book</h2>
    <p>お気に入りの本について投稿しよう</p>
    <%= link_to "Coming soon!", "#", class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div class="search-area mx-auto">
  <%= form_tag(path, method: :get) do %>
    <%= label_tag(:q, search_title) %>
    <%= text_field_tag(:q, "", class: "form-control" ) %>
    <%= submit_tag "検索", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<div class="stats">
  <%= link_to following_user_path(user) do %>
    <strong id="following" class="stat">
      <%= user.following.count %>
    </strong>
    following
  <% end %>
  |
  <%= link_to followers_user_path(user) do %>
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    followers
  <% end %>
</div>