config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "notifications/:id/link_through", to: "notifications#link_through", as: :link_through
  devise_for :users
  resources :users, only: [:edit, :update, :show] do
    member do
      get :following, :followers
    end
    resources :likes, only: [:index], shallow: true
  end
  resources :music, only: [:index]
  resources :movie, only: [:index]
  resources :posts, only: [:new, :create, :destroy] do
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  enum track_type: { movie: 0, music: 1 }
  validates :artistName, presence: true
  validates :trackName, presence: true
  validates :trackId, presence: true
  validates :genre, presence: true
  validates :artwork, presence: true
  validates :content, presence: true, length: { maximum: 400 }

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  POSTS_PER_PAGE = 6
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]

  def new
    @track = params[:track]
    @post = current_user.posts.build if user_signed_in?
    @posts = Post.where(trackId: @track["trackId"]).order(created_at: :desc).page(params[:page]).per(POSTS_PER_PAGE)
  end

  def create
    post = current_user.posts.build(post_params)
    if post.save
      flash[:notice] = "投稿が完了しました。"
      redirect_to request.referrer
    else
      flash[:alert] = "投稿に失敗しました。"
      redirect_to request.referrer
    end
  end

  def destroy
    @post.destroy
    redirect_to request.referrer || root_url
  end

  def show
  end

  private

  def post_params
    params.require(:post).permit(:content, :artistName, :artistId, :trackName, :trackId, :collectionId, :track_type, :genre, :artwork)
  end

  def correct_user
    @post = Post.find(params[:id])
    redirect_to root_path unless @post.user == current_user
  end
end

app/views/posts/_post.html.erb
<div class="user-info">
  <%= link_to new_post_path(track: LookupTrack.search_by_trackid(post.trackId, post.track_type)) do %>
    <%= image_tag post.artwork %>
    <h4> <%= post.trackName %></h4>
  <% end %>
  <h5><%= link_to post.artistName, (post.track_type == "movie" ? movie_index_path : music_index_path(artist_id: post.artistId)) %></h5>
  <% if current_user %>
    <div id="post-comment-<%= post.id.to_s %>" class="post-comment">
      <%= link_to image_tag("comment.png", size: "33x33", alt: "コメント一覧"), post_comments_path(post), class: "comment" %>
      <p><%= post.comments.size %>件</p>
    </div>
    <div id="post-like-<%= post.id.to_s %>" class="post-like">
      <% if post.liked_by(current_user).present? %>
        <%= link_to image_tag("heart.png", size: "30x30", alt: "いいね取り消し"), like_path(post.liked_by(current_user)), method: :delete, remote: true, class: "no-love" %>
      <% else %>
        <%= link_to image_tag("no-heart.png", size: "30x30", alt: "いいね"), post_likes_path(post), method: :post, remote: true, class: "love" %>
      <% end %>
      <p><%= post.likes.size %>件</p>
    </div>
  <% end %>
</div>
<div class="content">
  <%= simple_format(post.content) %>
</div>
<div class="post-bottom">
<%= link_to user_path(post.user) do %>
  <div class="post-user-info">
    <%= image_tag post.user.image.thumb.url, size: "50x50" ,class: "rounded-circle" %>
    <h6><%= post.user.username %></h6>
  </div>
<% end %>
<% if post.user == current_user %>
  <%= link_to "投稿削除", post, method: :delete, data: {confirm: "削除してよろしいですか？"}, class: "delete-button" %>
<% end %>
</div>

app/views/posts/_post_list.html.erb
<ul class="row">
  <% @posts.each do |post| %>
    <li>
      <%= render "posts/post", post: post %>
    </li>
  <% end %>
</ul>
<%= paginate @posts %>

app/views/posts/new.html.erb
<%= provide(:title, @track["trackName"]) %>
<div class="track-title mx-auto">
  <%= image_tag @track["artworkUrl100"] %>
  <%= link_to "今すぐ視聴する", @track["previewUrl"], target: "_blank", class: "btn btn-success" %>
  <h2><%= @track["trackName"] %>/<%= @track["artistName"] %></h2>
</div>

<% if user_signed_in? %>
  <div class="post-form mx-auto">
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.hidden_field :artistName, value: @track["artistName"] %>
        <%= f.hidden_field :artistId, value: @track["artistId"] %>
        <%= f.hidden_field :trackName, value: @track["trackName"] %>
        <%= f.hidden_field :trackId, value: @track["trackId"] %>
        <%= f.hidden_field :collectionId, value: @track["collectionId"] %>
        <%= f.hidden_field :genre, value: @track["primaryGenreName"] %>
        <%= f.hidden_field :artwork, value: @track["artworkUrl60"] %>
        <% if @track["kind"] == "feature-movie" %>
          <%= f.hidden_field :track_type, value: "movie" %>
        <% elsif @track["kind"] == "song" %>
          <%= f.hidden_field :track_type, value: "music" %>
        <% end %>

        <%= f.label :content, "投稿文" %>
        <%= f.text_area :content, class: "form-control", maxlength: 400 %>
      </div>

      <%= f.submit "投稿する", class: "btn btn-primary" %>
    <% end %>
  </div>
<% else %>
  <%= link_to "投稿するにはログインが必要です", root_path %>
<% end %>

<div class="post-list">
  <h3 class="text-center posts-count"><%= @track["trackName"] %>に関する投稿： <%= @posts.count %>件</h3>
  <%= render 'posts/post_list' %>
</div>