config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "notifications/:id/link_through", to: "notifications#link_through", as: :link_through
  devise_for :users
  resources :users, only: [:edit, :update, :show] do
    member do
      get :following, :followers
    end
    resources :likes, only: [:index], shallow: true
  end
  resources :music, only: [:index]
  resources :movie, only: [:index]
  resources :posts, only: [:new, :create, :destroy] do
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top">
  <%= link_to "FavCon", root_path, class: "navbar-brand" %>
  <%= render "notifications/notification_dropdown" if current_user %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto mx-auto">
      <% if current_user %>
        <li class="nav-item active">
          <%= link_to "Mypage", user_path(current_user), class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item active">
        <%= link_to "Movie", movie_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Music", music_index_path, class: "nav-link" %>
      </li>
      <% if current_user %>
        <li class="nav-item active">
          <%= link_to "Setting", edit_user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Logout", destroy_user_session_url, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_url, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=0.5,user-scalable=yes,initial-scale=1.0" />
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>

    <div class="main-wrapper">

      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>